[package]
name = "fn_grad"
version = "0.1.3"
edition = "2021"
description = "A trait for functions that have a gradient"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]